"""Add description to MeetingRoom

Revision ID: f3b6544856a9
Revises: bd6a3cdf1afd
Create Date: 2022-12-27 21:45:37.039661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b6544856a9'
down_revision = 'bd6a3cdf1afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MeetingRoom', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MeetingRoom', 'description')
    # ### end Alembic commands ###
